input("Hi please enter your name: ")
name = input("Hi please enter your name: ")
print(f"Hello, {name}!")
age = input("Hi please enter your age: ")
print(f"You are {age} years old.")
favorite_color = input("Hi please enter your favorite color: ")
print(f"Your favorite color is {favorite_color}.")
hobby = input("Hi please enter your hobby: ")
print(f"Your hobby is {hobby}.")

print("Thank you for sharing your information!")
print("Here is a summary of your input:")
print(f"Name: {name}")
print(f"Age: {age}")
print(f"Favorite Color: {favorite_color}")    